### ISSUE TITLE
confirmPayment WS

### ISSUE THREAD

**Issue by puttiam** [puttiam/Fruitrouge-API#25]
@ggrason can you explain how to work with order ws (registerOrder, listOrders, getOrder)? Tell me more about their response.
Does it works at the moment?

**Comment by ggrason** [comment]
*working on it*

**Comment by ggrason** [comment]
listOrders should only be used in the profile to list previous orders. getOrder completes it by allowing you to display information on a specific previous order.

I need to work on registerOrder, which should not exists as is, I need to work on the whole order/payment/validation part. That was the final part, for which we weren't sure to do it with html browsing or using our payment system's JDK.

**Comment by ggrason** [comment]
I checked registerOrder which is okay to simply create the order in our backoffice and get order ID and order amount.

Then you can use Be2Bill JDK to confirm this payment.
Can we discuss the moment you comes back from Be2Bill to confirm the order ? Because that is what is required, after registerOrder the order is in a state "waiting for payment" which only lasts 30 minutes, it needs to be confirmed or it is deleted after 30 minutes. So I need a confirmation to validate the order after payment.

I simply have no idea at all how the JDK works.

**Comment by puttiam** [comment]
@ggrason App get notification when payment is completed or failed. Response has `message`, `oder ID`, `transaction ID`
So you can create WS "confirmPayment" with parameters: `oder ID`, `confirmed` (int 0 - failed, 1 - confirmed), `message`, `transaction ID` (if needed)

**Comment by ggrason** [comment]
Can you tell me the purpose of confirmPayment, what do you expect as a result ?

As I understand I shall receive the order ID, message and transaction ID (yep send it too) and know if it succeeded or failed.
Then, if failed I shall do nothing actually, since you just have to tell the user it failed and let him go back to its basket, if it succeeds I shall just validate the order on our side and empty the basket.

Then, what should I display/return ?

**Comment by puttiam** [comment]
I need response message {0, Payment confirmed} if success or {1, Payment not confirmed} if fail. 
Agree, parameter `confirmed` is useless.

**Comment by ggrason** [comment]
confirmPayment WS is added and takes Be2Bill JDK response as parameters. For example:
{"CLIENTEMAIL":"testios@gmail.com","EXECCODE":"0000","MESSAGE":"The+transaction+has+been+accepted.","ORDERID":"56903811","TRANSACTIONID":"A1474242"}
